config/routes.rb
Flog::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "posts#index", :page => '1'

  resource :comments
  
  # posts by page
  match '/page(/:page)' => "posts#index",
    :page => /\d{1,}/, 
    :defaults => {:page => '1'}
    
  # posts by date
  match '/:year(/:month(/:day))(/page/:page)' => "posts#index",
    :year => /\d{4}/, 
    :month => /\d{1,2}/,
    :day => /\d{1,2}/,
    :page => /\d{1,}/, 
    :defaults => {:page => '1'}  
    
   # posts by tag
  match '/tag/:tag(/page/:page)' => "posts#index",
    :tag => /[\w-]+/, 
    :page => /\d{1,}/, 
    :defaults => {:page => '1'}
    
  match '/:slug' => "posts#show", :as => :post

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, :counter_cache => true
  
  validates :name, :presence => true
  validates :email, :presence => true
  validates :content, :presence => true
  validates :post, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  ##############################################################################
  # Relations and callbacks
  ##############################################################################
  has_many :comments, :dependent => :destroy
  has_many :post_tags
  has_many :tags, :through => :post_tags,
    :after_remove => :decrease_tag_posts_count
  
  after_save    :update_tag_posts_count
  after_destroy :update_tag_posts_count
  
  def update_tag_posts_count
    tags.each do |tag|
      tag.update_posts_count
    end
  end
  
  def decrease_tag_posts_count(tag)
    tag.update_posts_count
  end
  
  ##############################################################################
  # Nested attributes
  ##############################################################################
  #  accepts_nested_attributes_for :tags,
  #    :reject_if => :all_blank,
  #    :allow_destroy => true
 

  ##############################################################################
  # Attatchements
  ##############################################################################
  has_attached_file :file,
    :styles => {
      :original => "1072x712>",
      :medium => "536x356>",
      :small => "268x178>",
      :thumb => "134x89>",
    }

  ##############################################################################
  # Validation
  ##############################################################################
  validates_attachment_presence :file
  validates_attachment_content_type :file, :content_type => ['image/jpeg', 'image/png']
  # not working
  validates_attachment_size :file, :less_than => 5.megabytes
  
  validates :title, :presence => true
  validates :slug, :presence => true, :uniqueness => {:case_sensitive => false}
  
  ##############################################################################
  # Setters/getters
  ##############################################################################
  
  # set title and slug
  def title=(value)
    self[:title] = value
    self[:slug] = value ? value.to_slug : nil 
  end
  
  # set tags
  def tags_as_string=(value)
    tags.clear
    if value
      value.split(',').each do |v|
        tag_name = v.strip
        tags << Tag.find_or_create_by_name(tag_name) unless tag_name.length == 0
      end
    end
  end
  
  def tags_as_string
    tags.collect(&:name).join(", ")
  end
  ##############################################################################
  # Scopes
  ##############################################################################
  
  # accepts params year, month, day
  # will accept params: tag
  # list published posts
  def self.published(params = {})
    query = includes(:tags).where('publish = ?', true)   
      .where('publication_date <= ?', Time.now)
      .order('publication_date DESC')
      
    year  = params[:year].to_i  if params[:year]
    month = params[:month].to_i if params[:month]
    day   = params[:day].to_i   if params[:day]
    
    # query by date
    if day 
      date = Date.new(year, month, day).to_s + "%"    
    elsif month # query the intire month
      init_date = Date.new year, month, 1
      end_date = (init_date + 1.month) - 1.day
    elsif year # query for an intire year
      # first day of the given year
      init_date = Date.new year, 1, 1
      # last day of the given year 
      end_date = (Date.new year + 1) - 1.day
    end
   
    if date
      query = query.where('publication_date like ?', date )
    elsif init_date && end_date
      query = query.where('publication_date >= ? AND publication_date <= ?', init_date, end_date )
    end
    
    # query by tag
    tag = params[:tag] if params[:tag] 
    if tag
      query = query.where("tags.slug = ?", tag)
    end
    
    query
  end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  self.table_name =  :posts_tags
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, :through => :post_tags

  validates :name, 
    :presence => true, 
    :uniqueness => {:case_sensitive => false}
    
  validates :slug, 
    :presence => true, 
    :uniqueness => {:case_sensitive => false}  
  
  # updates posts_count
  # if posts_count == 0, the tag must be destroyed  
  def update_posts_count
    count = posts.count
    if count > 0 
      self[:posts_count] = count
      save
    else
      destroy
    end  
  end
  
  
  def name=(name)
    if name 
      self[:name] = name
      self[:slug] = name.to_slug
    else
      self[:name] = nil
      self[:slug] = nil  
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :set_params
  
  def set_params 
    params[:limit] = 1 unless params[:limit]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout "posts"
  
  def create
    attributes = params[:comment]
    @post = Post.find(attributes[:post_id])
    @comment = @post.comments.build(attributes)
    
    if @comment.save
      redirect_to post_path(@post.slug)
    else
      render 'posts/show'    
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  layout "posts"
  
  def index
    page = params[:page]  || 1
    per  = params[:limit] || 10
    @posts = Post.published(params).page(page).per(per)
  end
  
  def show
    @post = Post.find_by_slug(params[:slug])
    @post.comments.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) {page_title}
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  # set the title of the listed posts
  def set_post_list_title
    if @posts.size > 0 
      if params[:tag]
        #tag title
        title("#{@posts.first.tags.first.name}") 
      elsif params[:year]
        # time title
        if params[:day]
          date = Date.new(params[:year].to_i,params[:month].to_i,params[:day].to_i)
          title("#{date.to_formatted_s(:long_ordinal)}")
        elsif params[:month]
          title("#{params[:year]}/#{params[:month]}")
        else
          title("#{params[:year]}")
        end
      else
        title(t("All posts"))  
      end
    else
      title t("No posts found")
    end
  end
  
  # format post description
  def description(post) 
    simple_format(post.description)
  end
  
end

app/helpers/tags_helper.rb
module TagsHelper
  def tags_menu(order = 'name')
    ul = ['<ul class="tags"><li>']
    lis = [link_to(t("All"), root_path)]
    
    Tag.order(order).each do |tag|
      lis << link_to_tag(tag)
    end
    ul << lis.join('</li><li>')
    ul <<"<li></ul>"
    raw ul.join("\n")
  end
  
  def link_to_tag(tag, include_counter = true)
    if include_counter
      link_to(raw("#{tag.name} <span class=\"tag_posts_count\">(#{tag.posts_count})</span>"), "/tag/#{tag.slug}")
    else
      link_to(tag.name, "/tag/#{tag.slug}")
    end  
  end
  
  def link_to_tags(tags)
    links = []
    tags.each do |tag|
      links << link_to_tag(tag, false)
    end
    raw links.join(', ')
  end
end

app/views/comments/_form.html.erb
<div class="form">
	<%= semantic_form_for(@post.comments.last, 
	  :url => "#{comments_path}#new_comment") do |f| %>
		<%= f.inputs :name => 'Tell me what you think' do %>
			<%= f.input :post_id, :as => :hidden %>
			<%= f.input :name, :placeholder => "Type your name" %>
			<%= f.input :email, :placeholder => "Type your email address", 
				:hint => "Will not be displayed" %>
			<%= f.input :content, :placeholder => "Type your message" %>
			<%= f.buttons %>
		<% end %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flog - <%= yield(:title) ||  "welcome" %></title>
  <%= stylesheet_link_tag    "posts", :media => "all" %>
  <%= javascript_include_tag "posts" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="wrapper">
    <div class="header">
      <p>Simple Flog</p>
    </div>
    <div class="sidebar left"></div>
    <div class="content">
      <h1><%= yield :title %></h1>
      <%= yield %>
    </div>
    <div class="sidebar right">
      <div class="block advertisement">
        <p>This is an advertisement.</p>
      </div>
    
      <div class="tags_menu"><%= tags_menu %></div>
      
      <div class="block advertisement">
        <p>This is an advertisement.</p>
      </div>
      
    </div>
    <div class="footer">
      <p>Thank you for your visit!</p>
    </div>  
  </div>
  
</body>
</html>

app/views/posts/_comment_form.html.erb
<div class="form">
	<%= semantic_form_for(@post.comments.build) do |f| %>
		<%= f.inputs :name => 'Tell me what you think' do %>
			<%= f.input :post_id, :as => :hidden %>
			<%= f.input :name, :placeholder => "Type your name" %>
			<%= f.input :email, :placeholder => "Type your email address", 
				:hint => "Will not be displayed" %>
			<%= f.input :content, :placeholder => "Type your message" %>
			<%= f.buttons %>
		<% end %>
	<% end %>
</div>

app/views/posts/_comments.html.erb
  <% @post.comments.each do |comment| %>
    <% if comment.id.present? %>
    <div class="comment">
      <div class="author">
        <%= comment.name %> <%= t("commented on") %> <div class="time"><%= comment.created_at %>:</div>
      </div>
    
      <div class="content">
        <%= comment.content %>
      </div>
    </div>
    <% end %>
  <% end %>

app/views/posts/_tags.html.erb
<% if post.tags.all.size > 0 %>
<div class="tags">
	<p><strong>Tags:</strong> <%= link_to_tags(post.tags.all) %></p>
</div>
<% end %> 

app/views/posts/index.html.erb
<% set_post_list_title %>

<%= paginate @posts %>

<div class="posts">
<% @posts.each do |post| %>
  <div class="post">
  
    <%= link_to(post_path(post.slug)) do %>
      <h2><%= post.title %></h2>
    <% end %>
    
    
    <%= link_to(post_path(post.slug)) do %>
      <div class="image"><%= image_tag post.file.url(:medium), :alt => post.title, :title => post.title %></div>
    <% end %>

    <div class="description"><p><%= description(post) %></p></div>
    
	<%= render :partial => "tags", :locals => {:post => post} %>
	
    <div class="publication_date">
            <p><%= t("posted on") %> <span class="time"><%= post.created_at %>:</span></p>
    </div>
    
    <% if post.comments_count > 0 %>
      <%= link_to(post_path(post.slug) + "#comments") do %>
        <div class="commetns counter"><%= pluralize(post.comments_count, t('comment')) %></div>
      <% end %>
    <% end %>
    
    

  </div>
  <div class="post_separator"></div>
<% end %>
</div>

<%= paginate @posts %>

app/views/posts/show.html.erb
<% title(@post.title) %>
  <div class="post">
      <div class="image"><%= image_tag @post.file.url(:medium), :alt => @post.title, :title => @post.title %></div>
    <div class="description"><p><%= description(@post) %></p></div>
	<%= render :partial => "posts/tags", :locals => {:post => @post} %>
    <div class="publication_date">
      <p><%= t("commented on") %> <span class="time"><%= @post.created_at %>:</span></p>
      </div>
    </div>
  </div>
  
  <div class="comments" id="comments">
    <%= render :partial => "posts/comments", :locals => {:post => @post} %>
    <%= render :partial => "comments/form", :locals => {:post => @post} %>
  </div>
  